### ISSUE TITLE
Designed to work well with polyglots

### ISSUE THREAD

**Issue by aaronryank** [SatansSon/Commentator#2]
This language is 'designed to work well with polyglots'. However...

    # Converts active to a Unicode character and outputs it

`#` is a comment in most languages. Having a comment output a null byte when it's the first character in a program isn't good.

**Comment by cairdcoinheringaahing** [comment]
@aaronryank wait, someone actually used this O.o I was thinking of swapping `#` and `*/` given that `*/` needs `/*` to work as a comment in C. What do you think?

**Comment by aaronryank** [comment]
I'm working on [this](https://codegolf.stackexchange.com/a/137874/61563), using everything on TIO that's compatible.

I think that something aside from comments should be used for outputting, something more obscure. Comments, whether they be `//` or `#` or `/*` or `*/` could/should be used for something that's necessary yet easily reversible, such as incrementing the top of stack (or accumulator, whichever this language uses, I forgot as I've seen 50 language specs today.)

**Comment by cairdcoinheringaahing** [comment]
I've now swapped `#` with `/*` and vice versa, to make the polyglotting easier. If you wouldn't mind, could you ask Dennis to pull the TIO page? (You may have to change the code you linked to, in order to make it work.)

**Comment by aaronryank** [comment]
Sure, no problem. Sorry about your suspension btw :(

**Comment by cairdcoinheringaahing** [comment]
@aaronryank For the Hello, World program, could you tell Dennis that it should work if you swap the `#` and the `/*` symbols around. Man, I hate this suspension! 16 days left. D:
